### ISSUE TITLE
Ghidra 9.1.1

### ISSUE THREAD

**Issue by qwertymodo** [Gekkio/GhidraBoy#2]
Ghidra has been updated to 9.1.1 (20191218) which won't allow the latest version of this extension to be installed.  I'm not sure if it's just a matter of updating the metadata, or if there are actually any breaking changes, but it would be nice to have an up-to-date package.

**Comment by Gekkio** [comment]
Now available https://github.com/Gekkio/GhidraBoy/releases/tag/20200122_ghidra_9.1.1 :smile: 
Didn't require any actual changes, but Ghidra can happily install this release since versions match.
